apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:13.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: _DBSUA_SENHA_DO
            - name: POSTGRES_USER
              value: SEU_USER_DO_DB
            - name: POSTGRES_DB
              value: SEU_DATABASE

---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 10
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: davicarneiro/kube-news:v1
        ports:
        - containerPort: 8080
        env:
        - name: DB_DATABASE
          value: SEU_DATABASE
        - name: DB_PASSWORD
          value: SUA_SENHA_DO
        - name: DB_USERNAME
          value: SEU_USER_DO_DB
        - name: DB_HOST
          value: postgre

---
apiVersion: v1
kind: Service
metadata:
  name: kubenews
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
  type: NodePort

